#ifndef HID_USAGE_H
#define HID_USAGE_H

#define HID_USAGE_KEY_NONE 0x00
#define HID_USAGE_KEY_ESC 0x29
#define HID_USAGE_KEY_NUM_LOCK 0x53
#define HID_USAGE_KEY_KP_SLASH 0x54
#define HID_USAGE_KEY_KP_ASTERISK 0x55
#define HID_USAGE_KEY_KP_MINUS 0x56
#define HID_USAGE_KEY_KP_PLUS 0x57
#define HID_USAGE_KEY_KP_ENTER 0x58
#define HID_USAGE_KEY_KP_1 0x59
#define HID_USAGE_KEY_KP_2 0x5a
#define HID_USAGE_KEY_KP_3 0x5b
#define HID_USAGE_KEY_KP_4 0x5c
#define HID_USAGE_KEY_KP_5 0x5d
#define HID_USAGE_KEY_KP_6 0x5e
#define HID_USAGE_KEY_KP_7 0x5f
#define HID_USAGE_KEY_KP_8 0x60
#define HID_USAGE_KEY_KP_9 0x61
#define HID_USAGE_KEY_KP_0 0x62
#define HID_USAGE_KEY_KP_DOT 0x63
#define HID_USAGE_KEY_KP_EQUAL 0x67

#endif